// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Equipments;
using IsekaiTechnologies.FacCord.Core.Models.Storages;
using System.Threading.Tasks;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Equipments
{
    public interface IDrillRepository : IRepository<Drill>
    {
        Task<Item> GetStarterDrill();
    }
}
