// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Equipments;
using System.Threading.Tasks;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Equipments
{
    public interface IProspectorRepository : IRepository<Prospector>
    {
        Task<Prospector> GetStarterProspector();
    }
}
