// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Equipments;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Equipments
{
    public interface IRuptureChemicalRepository : IRepository<RuptureChemical>
    {

    }
}
