// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Mines;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Mines
{
    public interface IBlockSpawnChanceRepository : IRepository<BlockSpawnChance>
    {

    }
}
