// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Mines;
using System.Threading.Tasks;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Mines
{
    public interface IBlockRepository : IRepository<Block>
    {
        Task<Block> GetAsyncEagerly(long v);
        Task<Block> GetBlockByItemIdNameAsync(string id);
    }
}
