// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Mines;
using System.Threading.Tasks;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Mines
{
    public interface IRegionRepository : IRepository<Region>
    {
        Task<Region> GetStarterRegion();
    }
}
