// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Machines;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Machines
{
    public interface IMachineUnitRepository : IRepository<MachineUnit>
    {

    }
}
