// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models.Shops;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories.Shops
{
    public interface IListingRepository : IRepository<Listing>
    {

    }
}
