// Generated by struct?.GetType() simple repo parttern generator!
using IsekaiTechnologies.FacCord.Core.Models;

namespace IsekaiTechnologies.FacCord.Core.DAL.Repositories
{
    public interface IPlayerSettingsRepository : IRepository<PlayerSettings>
    {

    }
}
